version: '3.8'

services:
  bestsocialbot:
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: '256M'
    build: .
    container_name: bestsocialbot
    restart: unless-stopped
    env_file: .env
    environment:
      - BOT_NAME=${BESTHOME_TOKEN}
      - BOT_TOKEN=8555035433:AAHZBgE_nfEHt0WJopirjd0arp7XqsAhY6I
    volumes:
      - besthome_data:/data
      - .:/app

volumes:
  besthome_data:
