version: '3.8'

services:
  gifthealthbot:
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: '256M'
    build: .
    container_name: gifthealthbot
    restart: unless-stopped
    environment:
      - BOT_NAME=gifthealthbot
      - BOT_TOKEN=${MAIN_BOT_TOKEN}
    volumes:
      - wond_data:/data
      - .:/app

volumes:
  wond_data:
