services:
  gifthealthbot:
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: '256M'
    build: .
    container_name: gifthealthbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - BOT_NAME=gifthealthbot
    volumes:
      - .:/app
      - ../shared_storage:/shared_storage
