services:
  investmentsbot:
    deploy:
      resources:
        limits:
          cpus: '0.33'
          memory: '256M'
    build: .
    container_name: investmentsbot
    restart: unless-stopped
    environment:
      - BOT_NAME=investmentsbot
      - BOT_TOKEN=${MAIN_BOT_TOKEN}
    volumes:
      - investmentsbot_data:/data
      - .:/app

volumes:
  investmentsbot_data:
